// Nome: Tiago Eloy Possidonio Pereira - RA: 2417677

import javax.swing.JOptionPane;

public class Administrar_Tabuleiro extends javax.swing.JFrame {

    private BancoDeDados_Jogos bdTabuleiro = BancoDeDados_Jogos.getInstance();
    private Jogo_Tabuleiro tabuleiro = new Jogo_Tabuleiro();
    private boolean verificador = true;
    private static Administrar_Tabuleiro instancia;
    
    private Administrar_Tabuleiro() {
        initComponents();
    }

    public static Administrar_Tabuleiro getAdministrar_Tabuleiro() {
        if(instancia == null) {
            instancia = new Administrar_Tabuleiro(); 
        }
        return instancia;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel_Titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_ID = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Nome = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jLabel_Marca = new javax.swing.JLabel();
        jTextField_Marca = new javax.swing.JTextField();
        jLabel_QtdJogadores = new javax.swing.JLabel();
        jTextField_QtdJogadores = new javax.swing.JTextField();
        jTextField_Manual = new javax.swing.JTextField();
        jLabel_Manual = new javax.swing.JLabel();
        jTextField_QtdDados = new javax.swing.JTextField();
        jLabel_QtdDados = new javax.swing.JLabel();
        jLabel_QtdPecas = new javax.swing.JLabel();
        jTextField_QtdPecas = new javax.swing.JTextField();
        jLabel_valor = new javax.swing.JLabel();
        jTextField_valor = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Jogos de Tabuleiro");

        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 0, 38)); // NOI18N
        jLabel_Titulo.setText("Jogos de Tabuleiro");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_ID.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel_ID.setText("ID:");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Nome.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel_Nome.setText("Nome......:");

        jLabel_Marca.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel_Marca.setText("Marca.....:");

        jLabel_QtdJogadores.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel_QtdJogadores.setText("Qtd. de Jogadores.:");

        jLabel_Manual.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel_Manual.setText("Manual..:");

        jLabel_QtdDados.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel_QtdDados.setText("Qtd. de Dados.......:");

        jLabel_QtdPecas.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel_QtdPecas.setText("Qtd. de Peças........:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Nome)
                    .addComponent(jLabel_Marca)
                    .addComponent(jLabel_Manual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Manual, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jTextField_Marca)
                    .addComponent(jTextField_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_QtdJogadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_QtdJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_QtdDados)
                            .addComponent(jLabel_QtdPecas))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_QtdPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_QtdDados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Nome)
                        .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_QtdPecas)
                        .addComponent(jTextField_QtdPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Marca)
                        .addComponent(jTextField_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_QtdDados)
                        .addComponent(jTextField_QtdDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Manual)
                    .addComponent(jTextField_Manual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_QtdJogadores)
                    .addComponent(jTextField_QtdJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jLabel_valor.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel_valor.setText("R$:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel_ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ID))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_valor))
                .addGap(14, 14, 14))
        );

        jButtonConsultar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonDeletar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel_Titulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        Consultar(tabuleiro);
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        Cadastrar();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        Deletar();
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        Alterar();
    }//GEN-LAST:event_jButtonAlterarActionPerformed
 public void Cadastrar(){
        verificador = true;
        while (verificador==true) {
            try {
                tabuleiro.setId(Integer.parseInt(jTextField_ID.getText()));
            }
            catch (Excecoes e) {
                e.ID_vazio();
                break;
            }
            try {
                tabuleiro.setNome(jTextField_Nome.getText());
            }
            catch (Excecoes e) {
                e.ID_vazio();
                break;
            }
            try {
                tabuleiro.setQntpecas(Integer.parseInt(jTextField_QtdPecas.getText()));
            } catch(Excecoes e) {
                e.qtd_Pecas();
                break;
            }     
            try {
                tabuleiro.setMarca(jTextField_Marca.getText());
            } catch (Excecoes e) {
                e.Marca_vazio();
                break;
            } 
            try {
                tabuleiro.setQntdados(Integer.parseInt(jTextField_QtdDados.getText()));
            } catch(Excecoes e){
                 e.qtd_Dados();
                 break;
            }
            try {
                tabuleiro.setManualRegras(jTextField_Manual.getText());
            } catch (Excecoes e) {
                e.restricao_manual();
                break;
            }
            try {
                tabuleiro.setQntPlayers(Integer.parseInt(jTextField_QtdJogadores.getText()));

            } catch (Excecoes e) {
                e.qtd_min_jogadores();
                break;
            }
            try {
                tabuleiro.setValor(Float.parseFloat(jTextField_valor.getText()));
                tabuleiro.adicionar_lucro();
            } catch (Excecoes e) {
                e.valor_invalido();
                break;
            }
            tabuleiro = bdTabuleiro.Cadastrar(tabuleiro);
            if(tabuleiro != null) {
                JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!");
                Limpar();
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Já possuí um item cadastrado com esse ID!");
                Limpar();
            }
            verificador = false;
        }
    }
    
    public void Consultar(Jogo_Tabuleiro tabuleiro){
        try {
            tabuleiro.setId(Integer.parseInt(jTextField_ID.getText()));
            tabuleiro = bdTabuleiro.Consultar(tabuleiro);
            if(tabuleiro != null) {
            jTextField_ID.setText(Integer.toString(tabuleiro.getId()));
            jTextField_Marca.setText(tabuleiro.getMarca());
            jTextField_QtdPecas.setText(Integer.toString(tabuleiro.getQntpecas()));
            jTextField_Nome.setText(tabuleiro.getNome());
            jTextField_QtdDados.setText(Integer.toString(tabuleiro.getQntdados()));
            jTextField_Manual.setText(String.valueOf(tabuleiro.getManualRegras()));
            jTextField_QtdJogadores.setText(Integer.toString(tabuleiro.getQntPlayers()));
            jTextField_valor.setText(String.valueOf(tabuleiro.getValor()));
            JOptionPane.showConfirmDialog(rootPane, "Os dados estão corretos?");
            Limpar();
            }      
            else {
                JOptionPane.showMessageDialog(null, "Não há nenhum item cadastrado com esse ID.", "Verifique se digitou corretamente.", 0 );
        }
        
    }
        catch (Excecoes NumberFormatExeption) {
            JOptionPane.showConfirmDialog(rootPane, "O ID deve ser um número inteiro.");
        }
    }

    public void Alterar(){
        try {
            tabuleiro.setId(Integer.parseInt(jTextField_ID.getText()));
            tabuleiro.setNome(jTextField_Nome.getText());
            tabuleiro.setQntpecas(Integer.parseInt(jTextField_QtdPecas.getText()));
            tabuleiro.setMarca(jTextField_Marca.getText());
            tabuleiro.setQntdados(Integer.parseInt(jTextField_QtdDados.getText()));
            tabuleiro.setManualRegras(jTextField_Manual.getText());
            tabuleiro.setQntPlayers(Integer.parseInt(jTextField_QtdJogadores.getText()));
            tabuleiro.setValor(Float.parseFloat(jTextField_valor.getText()));
        } catch (Excecoes e) {
            
        }       
        tabuleiro = bdTabuleiro.Alterar(tabuleiro);
        if (tabuleiro != null) {
            JOptionPane.showConfirmDialog(rootPane, "Item atualizado!");
        }
        else {
            JOptionPane.showConfirmDialog(rootPane, "Erro para atualizado!");
        }
        Limpar();
    }
    
    public void Deletar() {
        tabuleiro = bdTabuleiro.Deletar(tabuleiro);
        if(tabuleiro != null) {
            JOptionPane.showConfirmDialog(rootPane, "Item removido!");
        } else {
            JOptionPane.showConfirmDialog(rootPane, "Item não removido!");
        }
        Limpar();
    }
    
    public void Limpar(){
        jTextField_ID.setText(null);
        jTextField_Marca.setText(null);
        jTextField_Manual.setText(null);
        jTextField_Nome.setText(null);
        jTextField_QtdDados.setText(null);
        jTextField_QtdPecas.setText(null);
        jTextField_QtdJogadores.setText(null);
        jTextField_valor.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_Manual;
    private javax.swing.JLabel jLabel_Marca;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_QtdDados;
    private javax.swing.JLabel jLabel_QtdJogadores;
    private javax.swing.JLabel jLabel_QtdPecas;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_valor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Manual;
    private javax.swing.JTextField jTextField_Marca;
    private javax.swing.JTextField jTextField_Nome;
    private javax.swing.JTextField jTextField_QtdDados;
    private javax.swing.JTextField jTextField_QtdJogadores;
    private javax.swing.JTextField jTextField_QtdPecas;
    private javax.swing.JTextField jTextField_valor;
    // End of variables declaration//GEN-END:variables
}
